version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez row data source
    tables:
      - name: raw_gz_product
        description: product of greenweez / we have one row per products_id and we get the purchase price of the product (which is different from its selling price).
        columns:
          - name: products_id
            description: the unique identifier of the product.
            tests:
              - unique
              - not_null
          - name: purchse_price
            description: the purchase price of the product.

      - name: raw_gz_sales
        description: sales of greenweez / we have one row per products_id found in each orders_is.
        tests:
              - unique:
                  column_name: "(orders_id || '-' || pdt_id)"
        columns:
          - name: date_date
            description: the date of purchase
          - name: orders_id
            description: the unique identifier of the order/transaction.
          - name: pdt_id
            description: the unique identifier of the product in the order. A single product id appears only once in an order.
          - name: revenue
            description: the total income generated by a business through its sales of goods or services.
          - name: quantity
            description: the quantity of products purchased.
      - name: raw_gz_ship
        description: ship of greenweez / We have all the information about the shipping costs and the cost of the shipment or log. There is one line per order with its associated costs and fees.
        columns:
          - name: orders_id
            description: the unique identifier of the order.
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: the price the customer pays for shipping.
          - name: logcost
            description: the cost of preparing the parcel in the warehouse.
          - name: ship_cost
            description: the shipping cost paid by Greenweez to the carrier/transporter.
